services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: phonebook_sql
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: phonebook_api
  #   ports:
  #     - "5036:8080"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Production
  #     - ConnectionStrings__DefaultConnection=Server=db;Database=PhonebookDb;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=True;
  #   depends_on:
  #     - db
  #   networks:
  #     - app-network

networks:
  app-network:
